version: "0.2"
language: en
words:
  - T_mag
  - F_pos
  - T_att
dictionaries:
  - custom-dictionary
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
